[package]
name = "helpmate_tb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retroboard = "0.2.2" # need same shakmaty version
shakmaty = "0.21.1"
arrayvec = "0.7" 
map-of-indexes = "0.1.4" 
indicatif = "0.16.2"
dhat = "0.2.4"

[profile.release] # for profiling only # dhat
debug = 1