[package]
name = "helpmate_tb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retroboard = "0.2.2" # need same shakmaty version
shakmaty = "0.21.1"
arrayvec = { version = "0.7", features = ["serde"] }
indicatif = "0.16.2"
itertools = "0.10.3"
dhat = "0.2.4"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }

[profile.release] # for profiling only # dhat
debug = 1