[package]
name = "helpmate_tb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
retroboard = "0.1.3"
shakmaty = "0.20.2"
indicatif = "0.16.2"