[package]
name = "helpmate_tb"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2", features = ["derive"] }
retroboard = "0.2.5"
arrayvec = { version = "0.7", features = ["serde"] }
indicatif = "0.16.2"
itertools = "0.10.3"
env_logger = "0.9"
log = "0.4"
dhat = "0.2.4"
serde_json = "1"
serde = { version = "1.0", features = ["derive"] }
zstd = "0.11.2"
deku = "0.13.1"
positioned-io = "0.3"


[profile.release] # for profiling only # dhat
debug = 1