[alias]
slow-test = "test --profile dhat --features dhat -- --include-ignored"
gen-snap = "test --profile dhat --features dhat --features trycmd-overwrite --test cli_tests -- --ignored" # include `--ignored` to run test ignored by default 