// GENERATED BY https://github.com/kraktus/shakmaty-syzygy/blob/helpmate_tb/examples/get_info.rs

use shakmaty::{Piece, Color::*, Role::*};
use crate::{Material, Pieces};
use arrayvec::ArrayVec;
use std::collections::HashMap;

#[derive(Clone, PartialEq, Eq, Hash)]
pub struct GroupDataInfo {
    pub pieces: Pieces,
    pub order: [u8; 2],
}

type InfoTable = ArrayVec<ArrayVec<GroupDataInfo, 2>, 4>;

#[rustfmt::skip]
pub fn get_info_table() -> HashMap<Material, InfoTable> {
    [
     (Material::from_str("KQBBPvK").unwrap(), [
                     ArrayVec::from_iter([GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: Queen }, Piece { color: White, role: King }, Piece { color: Black, role: King }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }].into_iter().collect(),
        order: [4, 15]
    },GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: King }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: Black, role: King }, Piece { color: White, role: Queen }].into_iter().collect(),
        order: [0, 15]
    },
                     ].into_iter()),
                     ArrayVec::from_iter([GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: Queen }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: White, role: King }, Piece { color: Black, role: King }].into_iter().collect(),
        order: [1, 15]
    },GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: King }, Piece { color: White, role: Queen }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: Black, role: King }].into_iter().collect(),
        order: [0, 15]
    },
                     ].into_iter()),
                     ArrayVec::from_iter([GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: Queen }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: White, role: King }, Piece { color: Black, role: King }].into_iter().collect(),
        order: [2, 15]
    },GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: King }, Piece { color: White, role: Queen }, Piece { color: Black, role: King }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }].into_iter().collect(),
        order: [0, 15]
    },
                     ].into_iter()),
                     ArrayVec::from_iter([GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: Queen }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: White, role: King }, Piece { color: Black, role: King }].into_iter().collect(),
        order: [1, 15]
    },GroupDataInfo {
        pieces: [Piece { color: White, role: Pawn }, Piece { color: White, role: King }, Piece { color: White, role: Bishop }, Piece { color: White, role: Bishop }, Piece { color: White, role: Queen }, Piece { color: Black, role: King }].into_iter().collect(),
        order: [3, 15]
    },
                     ].into_iter()),].into_iter().collect()),

    ].into_iter().collect()
}